### ISSUE TITLE
error: expected identifier before numeric constant

### ISSUE THREAD

**Issue by harryhancock** [Infineon/TLE493D-3DMagnetic-Sensor#16]
Error upon compiling example code

.pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\./util/Tle493d_conf.h:50:16: error: expected identifier before numeric constant
  P, FF, CF, T, PD3, PD0, FRM,  //diagnosis (Diag)
                ^
.pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\./util/Tle493d_conf.h:50:16: error: expected '}' before numeric 
constant
.pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\./util/Tle493d_conf.h:50:16: error: expected unqualified-id before numeric constant
In file included from .pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\Tle493d.h:43:0,
                 from .pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\Tle493d_a2b6.h:5,
                 from .pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\Tle493d_a2b6.cpp:1:
.pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\./util/Tle493d_conf.h:77:7: error: 'RegMask_t' does not name a type
 const RegMask_t regMasks[] = {
       ^~~~~~~~~
.pio\libdeps\ATmega328PB\TLE493D-Magnetic-Sensor\src\./util/Tle493d_conf.h:153:1: error: expected declaration before 
'}' token
 }
 ^

**Comment by 9Volts9er** [comment]
Ok, I guess, I fixed it.
The problem was, that for Arduino boards (at least Arduino Uno) "PD0" and "PD3" are already defined. I simply renamed the constants here to "PD_0" and "PD_3" to avoid this conflict.

Nevertheless it wouldn't compile with just these changes, because in the `begin()` there are code lines for switching on the sensor by setting pin `LED2` to **HIGH**. This is fine for those MS2Go-Kits because for the XMC2Go `LED2` is defined. 
But for Arduino this is not the case, so I had to remove the switch on sequence from the `begin()`. 
Instead, I moved it to the example files, out commented, so the user can decide whether they are necessary or not.

See the changes in this commit: [Link](https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/commit/4572880d0095f3dc7bc0381517af3d5082148260)
