### ISSUE TITLE
Bug: TLE93_p2b6_A1 not working 

### ISSUE THREAD

**Issue by NSchnitzler** [Infineon/TLE493D-3DMagnetic-Sensor#21]
Hi there,

I tried to make a TLE493DP2B6A1 working with an Adafruit Feather. I used the actual Master branch and not the old release, because of the PR https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/pull/20.

My Code looks like this:

`
#include <Arduino.h>
#include <Tle493d.h>
#include <Tle493d_p2b6.h>
Tle493d_p2b6 Tle493dMagnetic3DSensor = Tle493d_p2b6(Tle493d::MASTERCONTROLLEDMODE, Tle493d::TLE493D_A1);

void setup() {
  Serial.begin(9600);
  while (!Serial);
  Tle493dMagnetic3DSensor.begin();
  Tle493dMagnetic3DSensor.enableTemp();
}

void loop() {
  Tle493dMagnetic3DSensor.updateData();

  Serial.print(Tle493dMagnetic3DSensor.getX());
  Serial.print(" ; ");
  Serial.print(Tle493dMagnetic3DSensor.getY());
  Serial.print(" ; ");
  Serial.println(Tle493dMagnetic3DSensor.getZ());
  delay(500);
}
`

I have also thief the Fast Mode, but the results is always:
`
-266.24 ; -266.24 ; -266.24
`

Has anyone an idea how to make the sensor work?

Thanks in advance!

best,
Norbert

**Comment by 9Volts9er** [comment]
Hi,
it could have multiple reasons, I have never tried this combination - Adafruit Feather and TLE493D-P2B6-A1.
- It might be an issue with the library running on an Adafruit Feather. Have you tried it with different sensor-/address-types?
- So you have the A1 type of the sensor? Or do you have an A0 type and want to reconfigure it to address A1?
- How does your Hardware setup look like? Which pins of the sensor are connected to which pins of the Feather? Which pullup resistors are you using? 
- Can you control the VDD of the sensor or is it directly connected to 3.3V? Because if it's connected directly to 3.3V then there might be some Interrupt-pulses on the SCL line. These may disturb your I2C lines before the Interrupt feature is disabled within the libraries `begin()`. If you cannot control the VDD of the sensor, you could try to call the `begin()` before the `while(!Serial);` .
- Can you try to also use a `Tle493dMagnetic3DSensor.disableCollisionAvoidance()` after the `begin()`? This would disable the Clock Stretching feature. I have read somewhere that this might not be supported properly by the Feather.

This are my ideas to the issue.
