### ISSUE TITLE
How to set short range mode?

### ISSUE THREAD

**Issue by HiramLeija** [Infineon/TLE493D-3DMagnetic-Sensor#23]
Hi. 
How could I configure the **short range mode** with this library?
I'm using the TLE493D W2B6 A0 sensor and I need to increase the sensitivity by setting the short range mode.

**Comment by 9Volts9er** [comment]
Hi,
unfortunately there is no function enabling this feature in this library.
However you can activate the short range mode with I²C commands.

For this you need to include the `Wire.h` and then put the following lines in your `setup()` directly after the `Tle493dMagnetic3DSensor.begin()`:
```
  Wire.beginTransmission(0x35);  //Address the sensor with 7-bit address 0x35
  Wire.write(0x10);  //Write to register 0x10
  Wire.write(0x18);  //Set TRIG to 0b01 (standard configuration) and set the X2 bit for increased sensitivity
  Wire.endTransmission();
```

The values you get from the library are now twice as large as the real magnetic field values. Therefore you need to divide those values by 2 in order to have the real values.
