### ISSUE TITLE
-266.24 just keeps appear in my serial monitor (TLE493D-W2B6A2)

### ISSUE THREAD

**Issue by ajayrwarrier** [Infineon/TLE493D-3DMagnetic-Sensor#31]
We have made a custom PCB that connects an ESP32 to TLE493D-W2B6 A2. We have made the schematic using the official datasheet. We are getting -256, 0 or -1 as output. we are using the latest GitHub official library, in the constructor we are providing 

Tle493d Tle493dMagnetic3DSensor = Tle493d(Tle493d::MASTERCONTROLLEDMODE,Tle493d::TLE493D_A2);

Will attach the schematic as well.

Please help.

```
/**
* For basic setup just create a Tle493d() object. If you want to use the wake up mode please use Tle493d_w2b6(). Also
* the setUpdateRate() method is slightly different for different variants
*/


#include <Tle493d.h>

Tle493d Tle493dMagnetic3DSensor = Tle493d(Tle493d::MASTERCONTROLLEDMODE,Tle493d::TLE493D_A2);

void setup() {
  Serial.begin(9600);
  while (!Serial);
  Tle493dMagnetic3DSensor.begin();
  Tle493dMagnetic3DSensor.enableTemp();
}

void loop() {
  Tle493dMagnetic3DSensor.updateData();

  Serial.print(Tle493dMagnetic3DSensor.getX());
  Serial.print(" ; ");
  Serial.print(Tle493dMagnetic3DSensor.getY());
  Serial.print(" ; ");
  Serial.println(Tle493dMagnetic3DSensor.getZ());
  
  delay(500);
}

```

![signal-2024-01-10-152712_002](https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/assets/20872405/60c681e8-79ad-4d13-82e3-4ee300dd1695)

**Comment by ajayrwarrier** [comment]
I have seen the resolved issues around A2B6 but we are using W2B6 and none of those solutions nor the official library seems to work.

**Comment by 9Volts9er** [comment]
Not sure if this issue is resolved, yet. It has been quite some time since I last looked into this repository, sorry.
Best way to find out what's going on, is to use an oscilloscope or a logic analyzer at the data pins.
I would guess that the time between setting VDD HIGH and configuring the sensor is too long. So the I²C hardware unit of the ESP might have problems with the Interrupt pulses from the sensor.
Can you try setting VDD HIGH directly before `Tle493dMagnetic3DSensor.begin();` ?
